            double complex t1 
            double complex t2 
            double complex t4 
            double complex t5 
            double complex t6 
            double complex t8 
            double complex t9 
            double complex t10 
            double complex t11 
            double complex t12 
            double complex t13 
            double complex t14 
            double complex t16 
            double complex t17 
            double complex t18 
            double complex t20 
            double complex t22 
            double complex t23 
            double complex t25 
            double complex t26 
            double complex t28 
            double complex t29 
            double complex t30 
            double complex t32 
            double complex t34 
            double complex t35 
            double complex t38 
            double complex t39 
            double complex t41 
            double complex t43 
            double complex t44 
            double complex t47 
            double complex t48 
            double complex t49 
            double complex t50 
            double complex t51 
            double complex t55 
            double complex t56 
            double complex t59 
            double complex t61 
            double complex t62 
            double complex t63 
            double complex t64 
            double complex t66 
            double complex t67 
            double complex t69 
            double complex t72 
            double complex t73 
            double complex t74 
            double complex t76 
            double complex t80 
            double complex t81 
            double complex t83 
            double complex t84 
            double complex t87 
            double complex t91 
            double complex t93 
            double complex t96 
            double complex t100 
            double complex t102 
            double complex t106 
            double complex t107 
            double complex t108 
            double complex t109 
            double complex t113 
            double complex t114 
            double complex t116 
            double complex t117 
            double complex t119 
            double complex t122 
            double complex t124 
            double complex t125 
            double complex t129 
            double complex t131 
            double complex t138 
            double complex t141 
            double complex t142 
            double complex t144 
            double complex t146 
            double complex t149 
            double complex t152 
            double complex t158 
            double complex t159 
            double complex t162 
            double complex t166 
            double complex t171 
            double complex t175 
            double complex t178 
            double complex t179 
            double complex t181 
            double complex t182 
            double complex t187 
            double complex t189 
            double complex t193 
            double complex t195 
            double complex t197 
            double complex t206 
            double complex t208 
            double complex t210 
            double complex t214 
            double complex t215 
            double complex t217 
            double complex t219 
            double complex t220 
            double complex t227 
            double complex t233 
            double complex t240 
            double complex t241 
            double complex t245 
            double complex t247 
            double complex t249 
            double complex t260 
            double complex t261 
            double complex t264 
            double complex t266 
            double complex t271 
            double complex t274 
            double complex t279 
            double complex t283 
            double complex t288 
            double complex t299 
            double complex t300 
            double complex t325 
            double complex t328 
            double complex t331 
            double complex t334 
            double complex t337 
            double complex t339 
            double complex t350 
            double complex t351 
            double complex t355 
            double complex t358 
            double complex t360 
            double complex t363 
            double complex t372 
            double complex t379 
            double complex t383 
            double complex t386 
            double complex t389 
            double complex t394 
            double complex t409 
            double complex t414 
            double complex t425 
            double complex t426 
            double complex t427 
            double complex t428 
            double complex t429 
            double complex t431 
            double complex t433 
            double complex t435 
            double complex t437 
            double complex t439 
            double complex t441 
            double complex t444 
            double complex t448 
