            double complex t1 
            double complex t2 
            double complex t3 
            double complex t4 
            double complex t5 
            double complex t6 
            double complex t7 
            double complex t12 
            double complex t13 
            double complex t14 
            double complex t15 
            double complex t18 
            double complex t21 
            double complex t24 
            double complex t25 
            double complex t32 
            double complex t33 
            double complex t40 
            double complex t43 
            double complex t49 
            double complex t54 
            double complex t58 
            double complex t63 
            double complex t64 
            double complex t69 
            double complex t74 
            double complex t75 
            double complex t80 
            double complex t86 
            double complex t87 
            double complex t95 
            double complex t96 
            double complex t99 
            double complex t102 
            double complex t107 
            double complex t111 
            double complex t115 
            double complex t116 
            double complex t121 
            double complex t124 
            double complex t125 
            double complex t132 
            double complex t133 
            double complex t140 
            double complex t141 
            double complex t148 
            double complex t149 
            double complex t156 
            double complex t159 
            double complex t160 
            double complex t165 
            double complex t170 
            double complex t177 
            double complex t186 
            double complex t189 
            double complex t196 
            double complex t200 
            double complex t201 
            double complex t210 
            double complex t211 
            double complex t218 
            double complex t223 
            double complex t225 
            double complex t229 
            double complex t233 
            double complex t242 
            double complex t251 
            double complex t255 
            double complex t256 
            double complex t261 
            double complex t267 
            double complex t270 
            double complex t271 
            double complex t274 
            double complex t277 
            double complex t280 
            double complex t283 
            double complex t290 
            double complex t297 
            double complex t304 
            double complex t305 
            double complex t308 
            double complex t309 
            double complex t311 
            double complex t312 
            double complex t315 
            double complex t317 
            double complex t318 
            double complex t321 
            double complex t323 
            double complex t324 
            double complex t331 
            double complex t332 
            double complex t333 
            double complex t342 
            double complex t354 
            double complex t355 
            double complex t358 
            double complex t362 
            double complex t364 
            double complex t365 
            double complex t375 
            double complex t376 
            double complex t378 
            double complex t379 
            double complex t423 
            double complex t427 
            double complex t428 
            double complex t431 
            double complex t439 
            double complex t440 
            double complex t443 
            double complex t446 
            double complex t453 
            double complex t454 
            double complex t461 
            double complex t491 
            double complex t504 
            double complex t511 
            double complex t523 
            double complex t533 
            double complex t547 
            double complex t551 
            double complex t558 
            double complex t573 
            double complex t584 
            double complex t589 
            double complex t592 
            double complex t599 
            double complex t606 
            double complex t613 
            double complex t620 
            double complex t633 
            double complex t640 
            double complex t642 
            double complex t648 
            double complex t667 
            double complex t672 
            double complex t676 
            double complex t688 
            double complex t701 
            double complex t703 
            double complex t711 
