            double complex t1 
            double complex t2 
            double complex t7 
            double complex t9 
            double complex t15 
            double complex t16 
            double complex t19 
            double complex t21 
            double complex t24 
            double complex t32 
            double complex t45 
            double complex t46 
            double complex t47 
