            double complex t1 
            double complex t2 
            double complex t7 
            double complex t9 
            double complex t15 
            double complex t16 
            double complex t19 
            double complex t23 
            double complex t24 
            double complex t34 
            double complex t47 
            double complex t48 
