            double complex t1 
            double complex t3 
            double complex t4 
            double complex t7 
            double complex t11 
            double complex t13 
            double complex t17 
            double complex t20 
            double complex t38 
            double complex t43 
            double complex t45 
            double complex t46 
            double complex t54 
            double complex t63 
            double complex t68 
