            double complex t1 
            double complex t2 
            double complex t3 
            double complex t4 
            double complex t5 
            double complex t7 
            double complex t8 
            double complex t9 
            double complex t10 
            double complex t14 
            double complex t17 
            double complex t18 
            double complex t19 
            double complex t20 
            double complex t21 
            double complex t23 
            double complex t24 
            double complex t25 
            double complex t28 
            double complex t29 
            double complex t30 
            double complex t33 
            double complex t34 
            double complex t37 
            double complex t40 
            double complex t43 
            double complex t44 
            double complex t51 
            double complex t54 
            double complex t59 
            double complex t60 
            double complex t63 
            double complex t68 
            double complex t73 
            double complex t78 
            double complex t82 
            double complex t89 
            double complex t90 
            double complex t93 
            double complex t97 
            double complex t98 
            double complex t103 
            double complex t116 
            double complex t118 
            double complex t123 
            double complex t127 
            double complex t133 
            double complex t135 
            double complex t143 
            double complex t144 
            double complex t145 
            double complex t161 
            double complex t169 
            double complex t170 
            double complex t180 
            double complex t190 
            double complex t195 
            double complex t196 
            double complex t198 
            double complex t203 
            double complex t206 
            double complex t209 
            double complex t221 
            double complex t231 
            double complex t232 
            double complex t239 
            double complex t240 
            double complex t245 
            double complex t252 
            double complex t253 
            double complex t260 
            double complex t265 
            double complex t270 
            double complex t277 
            double complex t282 
            double complex t298 
            double complex t301 
            double complex t305 
            double complex t314 
            double complex t319 
            double complex t324 
            double complex t331 
            double complex t340 
            double complex t345 
            double complex t348 
            double complex t355 
            double complex t360 
            double complex t367 
            double complex t376 
            double complex t378 
            double complex t385 
            double complex t390 
            double complex t419 
            double complex t424 
            double complex t428 
            double complex t455 
            double complex t463 
            double complex t467 
            double complex t470 
            double complex t478 
            double complex t497 
