            double complex t1 
            double complex t6 
            double complex t8 
            double complex t14 
            double complex t17 
            double complex t20 
            double complex t22 
            double complex t27 
            double complex t39 
            double complex t42 
