      SUBROUTINE SGG_TTBZ(P1,ANS)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : g g -> t t~ z  
C  
C Crossing   1 is g g -> t t~ z  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NEXTERNAL,   NCOMB,     NCROSS         
      PARAMETER (NEXTERNAL=5, NCOMB= 48, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T, P(0:3,NEXTERNAL)
      REAL*8 GG_TTBZ
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB,NCROSS)
      DATA GOODHEL/THEL*.FALSE./
      DATA NTRY/0/
      DATA (NHEL(IHEL,  1),IHEL=1,5) / -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,  2),IHEL=1,5) / -1, -1, -1, -1,  0/
      DATA (NHEL(IHEL,  3),IHEL=1,5) / -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,  4),IHEL=1,5) / -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,  5),IHEL=1,5) / -1, -1, -1,  1,  0/
      DATA (NHEL(IHEL,  6),IHEL=1,5) / -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,  7),IHEL=1,5) / -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,  8),IHEL=1,5) / -1, -1,  1, -1,  0/
      DATA (NHEL(IHEL,  9),IHEL=1,5) / -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 10),IHEL=1,5) / -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 11),IHEL=1,5) / -1, -1,  1,  1,  0/
      DATA (NHEL(IHEL, 12),IHEL=1,5) / -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 13),IHEL=1,5) / -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 14),IHEL=1,5) / -1,  1, -1, -1,  0/
      DATA (NHEL(IHEL, 15),IHEL=1,5) / -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 16),IHEL=1,5) / -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 17),IHEL=1,5) / -1,  1, -1,  1,  0/
      DATA (NHEL(IHEL, 18),IHEL=1,5) / -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 19),IHEL=1,5) / -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 20),IHEL=1,5) / -1,  1,  1, -1,  0/
      DATA (NHEL(IHEL, 21),IHEL=1,5) / -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 22),IHEL=1,5) / -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 23),IHEL=1,5) / -1,  1,  1,  1,  0/
      DATA (NHEL(IHEL, 24),IHEL=1,5) / -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 25),IHEL=1,5) /  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 26),IHEL=1,5) /  1, -1, -1, -1,  0/
      DATA (NHEL(IHEL, 27),IHEL=1,5) /  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 28),IHEL=1,5) /  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL, 29),IHEL=1,5) /  1, -1, -1,  1,  0/
      DATA (NHEL(IHEL, 30),IHEL=1,5) /  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL, 31),IHEL=1,5) /  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL, 32),IHEL=1,5) /  1, -1,  1, -1,  0/
      DATA (NHEL(IHEL, 33),IHEL=1,5) /  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 34),IHEL=1,5) /  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 35),IHEL=1,5) /  1, -1,  1,  1,  0/
      DATA (NHEL(IHEL, 36),IHEL=1,5) /  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 37),IHEL=1,5) /  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 38),IHEL=1,5) /  1,  1, -1, -1,  0/
      DATA (NHEL(IHEL, 39),IHEL=1,5) /  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 40),IHEL=1,5) /  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 41),IHEL=1,5) /  1,  1, -1,  1,  0/
      DATA (NHEL(IHEL, 42),IHEL=1,5) /  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 43),IHEL=1,5) /  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 44),IHEL=1,5) /  1,  1,  1, -1,  0/
      DATA (NHEL(IHEL, 45),IHEL=1,5) /  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 46),IHEL=1,5) /  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 47),IHEL=1,5) /  1,  1,  1,  1,  0/
      DATA (NHEL(IHEL, 48),IHEL=1,5) /  1,  1,  1,  1,  1/
      DATA (  IC(IHEL,  1),IHEL=1,5) /  1,  2,  3,  4,  5/
      DATA (IDEN(IHEL),IHEL=  1,  1) / 256/
C ----------
C BEGIN CODE
C ----------
      NTRY=NTRY+1
      DO IPROC=1,NCROSS
      CALL SWITCHMOM(P1,P,IC(1,IPROC),JC,NEXTERNAL)
      DO IHEL=1,NEXTERNAL
         JC(IHEL) = +1
      ENDDO
      ANS(IPROC) = 0D0
      DO IHEL=1,NCOMB
          IF (GOODHEL(IHEL,IPROC) .OR. NTRY .LT. 2) THEN
             T=GG_TTBZ(P ,NHEL(1,IHEL),JC(1))            
             ANS(IPROC)=ANS(IPROC)+T
              IF (T .GT. 0D0 .AND. .NOT. GOODHEL(IHEL,IPROC)) THEN
                  GOODHEL(IHEL,IPROC)=.TRUE.
C             WRITE(*,*) IHEL,T
              ENDIF
          ENDIF
      ENDDO
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))
      ENDDO
      END
       
       
      REAL*8 FUNCTION GG_TTBZ(P,NHEL,IC)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : g g -> t t~ z  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN,    NEXTERNAL       
      PARAMETER (NGRAPHS=   8,NEIGEN=  2,NEXTERNAL=5)   
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=  15, NCOLOR=   2) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C  
      INCLUDE 'coupl.inc'
C  
C COLOR DATA
C  
      DATA Denom(1  )/            3/                                       
      DATA (CF(i,1  ),i=1  ,2  ) /    16,   -2/                            
C               T[3,4,2,1]                                                 
      DATA Denom(2  )/            3/                                       
      DATA (CF(i,2  ),i=1  ,2  ) /    -2,   16/                            
C               T[3,4,1,2]                                                 
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX(P(0,1   ),ZERO ,NHEL(1   ),-1*IC(1   ),W(1,1   ))        
      CALL VXXXXX(P(0,2   ),ZERO ,NHEL(2   ),-1*IC(2   ),W(1,2   ))        
      CALL OXXXXX(P(0,3   ),TMASS ,NHEL(3   ),+1*IC(3   ),W(1,3   ))       
      CALL IXXXXX(P(0,4   ),TMASS ,NHEL(4   ),-1*IC(4   ),W(1,4   ))       
      CALL VXXXXX(P(0,5   ),ZMASS ,NHEL(5   ),+1*IC(5   ),W(1,5   ))       
      CALL FVIXXX(W(1,4   ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,6   ))     
      CALL FVOXXX(W(1,3   ),W(1,5   ),GZU ,TMASS   ,TWIDTH  ,W(1,7   ))    
      CALL IOVXXX(W(1,6   ),W(1,7   ),W(1,2   ),GG ,AMP(1   ))             
      CALL FVOXXX(W(1,3   ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,8   ))     
      CALL FVOXXX(W(1,8   ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,9   ))     
      CALL IOVXXX(W(1,4   ),W(1,9   ),W(1,5   ),GZU ,AMP(2   ))            
      CALL IOVXXX(W(1,6   ),W(1,8   ),W(1,5   ),GZU ,AMP(3   ))            
      CALL FVIXXX(W(1,4   ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,10  ))     
      CALL IOVXXX(W(1,10  ),W(1,7   ),W(1,1   ),GG ,AMP(4   ))             
      CALL FVOXXX(W(1,3   ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,11  ))     
      CALL FVOXXX(W(1,11  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,12  ))     
      CALL IOVXXX(W(1,4   ),W(1,12  ),W(1,5   ),GZU ,AMP(5   ))            
      CALL IOVXXX(W(1,10  ),W(1,11  ),W(1,5   ),GZU ,AMP(6   ))            
      CALL JVVXXX(W(1,1   ),W(1,2   ),G ,ZERO    ,ZERO    ,W(1,13  ))      
      CALL FVIXXX(W(1,4   ),W(1,13  ),GG ,TMASS   ,TWIDTH  ,W(1,14  ))     
      CALL IOVXXX(W(1,14  ),W(1,3   ),W(1,5   ),GZU ,AMP(7   ))            
      CALL FVOXXX(W(1,3   ),W(1,13  ),GG ,TMASS   ,TWIDTH  ,W(1,15  ))     
      CALL IOVXXX(W(1,4   ),W(1,15  ),W(1,5   ),GZU ,AMP(8   ))            
      JAMP(   1) = -AMP(   1)-AMP(   2)-AMP(   3)+AMP(   7)+AMP(   8)
      JAMP(   2) = -AMP(   4)-AMP(   5)-AMP(   6)-AMP(   7)-AMP(   8)
      GG_TTBZ = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          GG_TTBZ =GG_TTBZ+ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO
C      CALL GAUGECHECK(JAMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NCOLOR,NEIGEN) 
      END
